### ISSUE TITLE
How to run after installation?

### ISSUE THREAD

**Issue by seanspotatobusiness** [rricharz/pi-gpio-display#2]
The instructions in the README say to install and reboot. After installation and rebooting, I cannot find the program in the program menu. How do I start the program? Thanks.

**Comment by rricharz** [comment]
There should be an item on the desktop after the installation, which you can click. Alternatively, you can type pi-gpio-display in a console window, or open home/pi/bin with the file manager and double click pi-gpio-display there.

**Comment by seanspotatobusiness** [comment]
There is no icon on the desktop and the CLI returns "bash: pi-gpio-display: command not found". I'm guessing this is because you can only use the program if you are logged in as user 'pi'? I did install it as user pi but I didn't realise it could only be used as user pi also.
